services:
  - type: web
    name: fastapi-worklog
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: DB_HOST
        value: worklog-db.cr6mewukevlp.us-east-2.rds.amazonaws.com
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        value: <SET_IN_RENDER_DASHBOARD>
      - key: DB_NAME
        value: worklog
      - key: OPENAI_API_KEY
        value: <SET_IN_RENDER_DASHBOARD>